In [2]:
import classSize as cs
from classSize import *
from importlib import reload
reload(cs)

In [21]:
df = generate()
df = df.drop(list(range(24))).reset_index(drop=True)
df.head(30)

,CSD,BORO,GRADE,PROGRAM TYPE,CORE SUBJECT (MS CORE and 9-12 ONLY),CORE COURSE (MS CORE and 9-12 ONLY),SERVICE CATEGORY(K-9* ONLY),NUMBER OF STUDENTS / SEATS FILLED,NUMBER OF SECTIONS,AVERAGE CLASS SIZE
0,1,M,MS Core,GEN ED,ENGLISH,MS English Core,-,811,32,25.3
1,1,M,MS Core,GEN ED,MATH,MS Math Core,-,882,38,23.2
2,1,M,MS Core,GEN ED,MATH,Integrated Algebra,-,144,6,24.0
3,1,M,MS Core,GEN ED,SCIENCE,MS Science Core,-,877,37,23.7
4,1,M,MS Core,GEN ED,SCIENCE,Living Environment,-,103,4,25.8
5,1,M,MS Core,GEN ED,SOCIAL STUDIES,MS Social Studies Core,-,783,33,23.7
6,1,M,MS Core,GEN ED,SOCIAL STUDIES,Global History & Geography,-,59,2,29.5
7,1,M,MS Core,GEN ED,SOCIAL STUDIES,US History & Government,-,36,2,18.0
8,1,M,MS Core,GEN ED,SOCIAL STUDIES,Participation in Government,-,26,1,26.0
9,1,M,MS Core,CTT,ENGLISH,MS English Core,-,321,13,24.7
10,1,M,MS Core,CTT,MATH,MS Math Core,-,428,19,22.5
11,1,M,MS Core,CTT,SCIENCE,MS Science Core,-,445,20,22.3
12,1,M,MS Core,CTT,SOCIAL STUDIES,MS Social Studies Core,-,368,16,23.0
13,1,M,MS Core,SPEC ED,ENGLISH,MS English Core,-,52,5,10.4
14,1,M,MS Core,SPEC ED,MATH,MS Math Core,-,67,6,11.2
15,1,M,MS Core,SPEC ED,SCIENCE,MS Science Core,-,67,6,11.2
16,1,M,MS Core,SPEC ED,SOCIAL STUDIES,MS Social Studies Core,-,45,4,11.3
17,1,M,09-12,GEN ED,ENGLISH,English 9,-,847,38,22.3
18,1,M,09-12,GEN ED,ENGLISH,English 10,-,1010,44,23.0
19,1,M,09-12,GEN ED,ENGLISH,English 11,-,615,27,22.8
20,1,M,09-12,GEN ED,ENGLISH,English 12,-,631,30,21.0
21,1,M,09-12,GEN ED,ENGLISH,MS English Core,-,20,1,20.0
22,1,M,09-12,GEN ED,ENGLISH,Other English,-,457,22,20.8
23,1,M,09-12,GEN ED,MATH,Integrated Algebra,-,807,34,23.7
24,1,M,09-12,GEN ED,MATH,Geometry,-,698,28,24.9
25,1,M,09-12,GEN ED,MATH,Trigonometry,-,572,23,24.9
26,1,M,09-12,GEN ED,MATH,Math A,-,183,8,22.9
27,1,M,09-12,GEN ED,MATH,Math B,-,96,5,19.2
28,1,M,09-12,GEN ED,MATH,Other Math,-,477,22,21.7
29,1,M,09-12,GEN ED,SCIENCE,Earth Science,-,574,23,25.0